// generated by go:generate, DO NOT EDIT

package mdm

import (
	"encoding/json"
	"fmt"
)

func (c *Command) MarshalPlist() (interface{}, error) {
	switch c.RequestType {

	case "DeviceInformation":
		return &struct {
			RequestType string
			DeviceInformation
		}{
			RequestType:       c.RequestType,
			DeviceInformation: c.DeviceInformation,
		}, nil

	case "InstallApplication":
		return &struct {
			RequestType string
			InstallApplication
		}{
			RequestType:        c.RequestType,
			InstallApplication: c.InstallApplication,
		}, nil

	case "InstallProfile":
		return &struct {
			RequestType string
			InstallProfile
		}{
			RequestType:    c.RequestType,
			InstallProfile: c.InstallProfile,
		}, nil

	case "RemoveProfile":
		return &struct {
			RequestType string
			RemoveProfile
		}{
			RequestType:   c.RequestType,
			RemoveProfile: c.RemoveProfile,
		}, nil

	case "InstalledApplicationList":
		return &struct {
			RequestType string
			InstalledApplicationList
		}{
			RequestType:              c.RequestType,
			InstalledApplicationList: c.InstalledApplicationList,
		}, nil

	case "AccountConfiguration":
		return &struct {
			RequestType string
			AccountConfiguration
		}{
			RequestType:          c.RequestType,
			AccountConfiguration: c.AccountConfiguration,
		}, nil

	case "ScheduleOSUpdateScan":
		return &struct {
			RequestType string
			ScheduleOSUpdateScan
		}{
			RequestType:          c.RequestType,
			ScheduleOSUpdateScan: c.ScheduleOSUpdateScan,
		}, nil

	case "ScheduleOSUpdate":
		return &struct {
			RequestType string
			ScheduleOSUpdate
		}{
			RequestType:      c.RequestType,
			ScheduleOSUpdate: c.ScheduleOSUpdate,
		}, nil

	case "EraseDevice":
		return &struct {
			RequestType string
			EraseDevice
		}{
			RequestType: c.RequestType,
			EraseDevice: c.EraseDevice,
		}, nil

	case "DeviceLock":
		return &struct {
			RequestType string
			DeviceLock
		}{
			RequestType: c.RequestType,
			DeviceLock:  c.DeviceLock,
		}, nil

	default:
		return nil, fmt.Errorf("unknown request type: %s", c.RequestType)
	}
}

func (c *CommandRequest) UnmarshalJSON(d []byte) error {
	var j struct {
		RequestType string `json:"request_type"`
	}
	if err := json.Unmarshal(d, &j); err != nil {
		return err
	}
	switch j.RequestType {

	case "DeviceInformation":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			DeviceInformation
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.DeviceInformation = x.DeviceInformation
		return nil

	case "InstallApplication":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			InstallApplication
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.InstallApplication = x.InstallApplication
		return nil

	case "AccountConfiguration":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			AccountConfiguration
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.AccountConfiguration = x.AccountConfiguration
		return nil

	case "ScheduleOSUpdateScan":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			ScheduleOSUpdateScan
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.ScheduleOSUpdateScan = x.ScheduleOSUpdateScan
		return nil

	case "ScheduleOSUpdate":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			ScheduleOSUpdate
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.ScheduleOSUpdate = x.ScheduleOSUpdate
		return nil

	case "InstallProfile":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			InstallProfile
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.InstallProfile = x.InstallProfile
		return nil

	case "RemoveProfile":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			RemoveProfile
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.RemoveProfile = x.RemoveProfile
		return nil

	case "InstallProvisioningProfile":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			InstallProvisioningProfile
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.InstallProvisioningProfile = x.InstallProvisioningProfile
		return nil

	case "RemoveProvisioningProfile":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			RemoveProvisioningProfile
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.RemoveProvisioningProfile = x.RemoveProvisioningProfile
		return nil

	case "InstalledApplicationList":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			InstalledApplicationList
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.InstalledApplicationList = x.InstalledApplicationList
		return nil

	case "DeviceLock":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			DeviceLock
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.DeviceLock = x.DeviceLock
		return nil

	case "ClearPasscode":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			ClearPasscode
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.ClearPasscode = x.ClearPasscode
		return nil

	case "EraseDevice":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			EraseDevice
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.EraseDevice = x.EraseDevice
		return nil

	case "RequestMirroring":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			RequestMirroring
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.RequestMirroring = x.RequestMirroring
		return nil

	case "Restrictions":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			Restrictions
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.Restrictions = x.Restrictions
		return nil

	case "DeleteUser":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			DeleteUser
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.DeleteUser = x.DeleteUser
		return nil

	case "EnableLostMode":
		var x struct {
			RequestType string `json:"request_type"`
			UDID        string `json:"udid"`
			EnableLostMode
		}
		if err := json.Unmarshal(d, &x); err != nil {
			return err
		}
		c.RequestType = x.RequestType
		c.UDID = x.UDID
		c.EnableLostMode = x.EnableLostMode
		return nil

	default:
		return fmt.Errorf("mdm: unknown request_type %s", j.RequestType)
	}
}
